apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=       # admin (Base64 encoded)
  POSTGRES_PASSWORD: YWRtaW4xMjM=  # admin123 (Base64 encoded)
  POSTGRES_DB: dXNlcl9kYg==      # user_db (Base64 encoded)
